# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connection.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(356, 176)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.status_label = QtWidgets.QLabel(Dialog)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 0, 0, 1, 1)
        self.label_ip_port = QtWidgets.QLabel(Dialog)
        self.label_ip_port.setObjectName("label_ip_port")
        self.gridLayout.addWidget(self.label_ip_port, 4, 0, 1, 1)
        self.ip_port_edit = QtWidgets.QLineEdit(Dialog)
        self.ip_port_edit.setObjectName("ip_port_edit")
        self.gridLayout.addWidget(self.ip_port_edit, 4, 1, 1, 3)
        self.random_port_checkBox = QtWidgets.QCheckBox(Dialog)
        self.random_port_checkBox.setObjectName("random_port_checkBox")
        self.gridLayout.addWidget(self.random_port_checkBox, 3, 2, 1, 1)
        self.status_label_out = QtWidgets.QLabel(Dialog)
        self.status_label_out.setObjectName("status_label_out")
        self.gridLayout.addWidget(self.status_label_out, 0, 1, 1, 1)
        self.port_edit = QtWidgets.QLineEdit(Dialog)
        self.port_edit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_edit.sizePolicy().hasHeightForWidth())
        self.port_edit.setSizePolicy(sizePolicy)
        self.port_edit.setObjectName("port_edit")
        self.gridLayout.addWidget(self.port_edit, 3, 1, 1, 1)
        self.label_port = QtWidgets.QLabel(Dialog)
        self.label_port.setObjectName("label_port")
        self.gridLayout.addWidget(self.label_port, 3, 0, 1, 1)
        self.connect_buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.connect_buttonBox.setEnabled(True)
        self.connect_buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.connect_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.connect_buttonBox.setObjectName("connect_buttonBox")
        self.gridLayout.addWidget(self.connect_buttonBox, 5, 0, 1, 3)

        self.retranslateUi(Dialog)
        self.connect_buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.connect_buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.status_label.setText(_translate("Dialog", "Status:"))
        self.label_ip_port.setText(_translate("Dialog", "IP and port:"))
        self.random_port_checkBox.setText(_translate("Dialog", "Random port"))
        self.status_label_out.setText(_translate("Dialog", "Text"))
        self.label_port.setText(_translate("Dialog", "Port:"))
