# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connection.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(397, 138)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ip_port_edit = QtWidgets.QLineEdit(Dialog)
        self.ip_port_edit.setObjectName("ip_port_edit")
        self.horizontalLayout.addWidget(self.ip_port_edit)
        self.horizontalLayout.setStretch(0, 4)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 2)
        self.label_ip_port = QtWidgets.QLabel(Dialog)
        self.label_ip_port.setObjectName("label_ip_port")
        self.gridLayout.addWidget(self.label_ip_port, 4, 0, 1, 1)
        self.random_port_checkBox = QtWidgets.QCheckBox(Dialog)
        self.random_port_checkBox.setObjectName("random_port_checkBox")
        self.gridLayout.addWidget(self.random_port_checkBox, 3, 2, 1, 1)
        self.heading_label = QtWidgets.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 248, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 248, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 248, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.heading_label.setPalette(palette)
        self.heading_label.setObjectName("heading_label")
        self.gridLayout.addWidget(self.heading_label, 0, 1, 1, 1)
        self.port_edit = QtWidgets.QLineEdit(Dialog)
        self.port_edit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.port_edit.sizePolicy().hasHeightForWidth())
        self.port_edit.setSizePolicy(sizePolicy)
        self.port_edit.setObjectName("port_edit")
        self.gridLayout.addWidget(self.port_edit, 3, 1, 1, 1)
        self.label_port = QtWidgets.QLabel(Dialog)
        self.label_port.setObjectName("label_port")
        self.gridLayout.addWidget(self.label_port, 3, 0, 1, 1)
        self.button_cancel = QtWidgets.QPushButton(Dialog)
        self.button_cancel.setObjectName("button_cancel")
        self.gridLayout.addWidget(self.button_cancel, 5, 1, 1, 1)
        self.button_ok = QtWidgets.QPushButton(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 13, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 13, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 13, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.button_ok.setPalette(palette)
        self.button_ok.setObjectName("button_ok")
        self.gridLayout.addWidget(self.button_ok, 5, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_ip_port.setText(_translate("Dialog", "IP:port сервера:"))
        self.random_port_checkBox.setText(_translate("Dialog", "Случайный порт"))
        self.heading_label.setText(_translate("Dialog", "Введите данные"))
        self.label_port.setText(_translate("Dialog", "Открыть порт:"))
        self.button_cancel.setText(_translate("Dialog", "Отмена"))
        self.button_ok.setText(_translate("Dialog", "ОК"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
