# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DrawOnline.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 523)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.button_pencil = QtWidgets.QPushButton(self.centralwidget)
        self.button_pencil.setObjectName("button_pencil")
        self.gridLayout.addWidget(self.button_pencil, 0, 0, 1, 1)
        self.button_eraser = QtWidgets.QPushButton(self.centralwidget)
        self.button_eraser.setObjectName("button_eraser")
        self.gridLayout.addWidget(self.button_eraser, 0, 1, 1, 1)
        self.spinBox_list = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_list.setObjectName("spinBox_list")
        self.gridLayout.addWidget(self.spinBox_list, 2, 3, 1, 1)
        self.button_connect = QtWidgets.QToolButton(self.centralwidget)
        self.button_connect.setCheckable(False)
        self.button_connect.setObjectName("button_connect")
        self.gridLayout.addWidget(self.button_connect, 0, 3, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 588, 380))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 4)
        self.verticalScroll = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScroll.setOrientation(QtCore.Qt.Vertical)
        self.verticalScroll.setObjectName("verticalScroll")
        self.gridLayout.addWidget(self.verticalScroll, 1, 4, 1, 1)
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        self.button_clear.setObjectName("button_clear")
        self.gridLayout.addWidget(self.button_clear, 0, 2, 1, 1)
        self.horizontalScroll = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScroll.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScroll.setObjectName("horizontalScroll")
        self.gridLayout.addWidget(self.horizontalScroll, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 24))
        palette = QtGui.QPalette()
        self.menubar.setProperty("Palette_1", palette)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.button_connect.triggered['QAction*'].connect(self.centralwidget.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_pencil.setText(_translate("MainWindow", "Pencil"))
        self.button_eraser.setText(_translate("MainWindow", "Eraser"))
        self.button_connect.setText(_translate("MainWindow", "Connect"))
        self.button_clear.setText(_translate("MainWindow", "Clear all"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
